### ISSUE TITLE
Edit Documentation

### ISSUE THREAD

**Issue by cybersol795** [djfurman/dotfiles#7]
Would you mind if I propose to edit readme.md? I am taking a technical writing course in university  and our assignment involves editing github project documentations to practice real world examples.
The goal is not to significantly change or remove any part of the technical information but to improve the structure of the writing or fix typos and grammatical issues. Edits may involve aspects like clarity and concision too. It will really help me if you allow me to contribute, make a few changes and submit a PR. Thanks!

**Comment by djfurman** [comment]
Hi, @cybersol795 please do! I'd welcome the PR and contribution. Feel free to utilize the readme or add additional docs if more appropriate. I'll happily review the PR when you get a chance to raise it.

Thanks for finding me and having the interest in technical writing!
